spring:
  application:
    name: ucloan

  config:
    import: "optional:file:./.env[.properties]"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 16

  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true

  threads:
    virtual:
      enabled: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000
      refresh-token:
        expiration: 604800000

logging:
  level:
    org.springframework.security: WARN
    